In [11]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [12]:
%matplotlib inline

In [35]:
provider=pd.read_csv("data/Medicare_Provider_Util_Payment_PUF_CY2017.txt", sep = "\t")

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
provider.head(10)

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,...,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,average_Medicare_standard_amt
0,1,CPT copyright 2016 American Medical Associatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99217,Hospital observation care discharge,N,100.0,96.0,100.0,73.398800,325.780000,56.827200,57.492400
2,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99218,Hospital observation care typically 30 minutes,N,26.0,25.0,26.0,100.080000,449.000000,78.460000,79.306154
3,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99219,Hospital observation care typically 50 minutes,N,52.0,51.0,52.0,136.380000,614.000000,102.807692,103.895385
4,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99220,Hospital observation care typically 70 minutes...,N,59.0,59.0,59.0,190.363729,755.932203,141.293559,142.865763
5,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99221,"Initial hospital inpatient care, typically 30 ...",N,16.0,16.0,16.0,101.680000,462.812500,79.710000,80.750000
6,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99222,"Initial hospital inpatient care, typically 50 ...",N,59.0,57.0,59.0,137.310000,625.000000,105.825424,107.070678
7,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99223,"Initial hospital inpatient care, typically 70 ...",N,114.0,110.0,114.0,206.061579,923.991228,160.377193,160.026316
8,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99232,"Subsequent hospital inpatient care, typically ...",N,627.0,233.0,627.0,72.622456,326.245614,56.366730,57.047895
9,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,...,99233,"Subsequent hospital inpatient care, typically ...",N,207.0,127.0,207.0,106.653913,461.072464,82.820676,83.196039

In [36]:
provider.tail(10)

,npi,nppes_provider_last_org_name,nppes_provider_first_name,nppes_provider_mi,nppes_credentials,nppes_provider_gender,nppes_entity_code,nppes_provider_street1,nppes_provider_street2,nppes_provider_city,...,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,average_Medicare_standard_amt
9847434,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99203,"New patient office or other outpatient visit, ...",N,37.0,37.0,37.0,80.91,143.0,56.712973,54.526216
9847435,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99203,"New patient office or other outpatient visit, ...",N,88.0,88.0,88.0,117.26,290.0,84.541023,79.799659
9847436,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99204,"New patient office or other outpatient visit, ...",N,83.0,83.0,83.0,137.24,284.0,102.023614,97.797711
9847437,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99204,"New patient office or other outpatient visit, ...",N,105.0,105.0,105.0,176.90,431.0,124.930381,117.928762
9847438,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99214,Established patient office or other outpatient...,N,103.0,84.0,103.0,83.40,198.0,61.235146,58.485243
9847439,1992999825,DESCHENES,GEOFFREY,R,M.D.,M,I,1100 9TH AVE,MS:M4-PFS,SEATTLE,...,99214,Established patient office or other outpatient...,N,248.0,175.0,248.0,116.86,345.0,85.637177,80.263065
9847440,1992999874,JOFFE,GABRIELLA,NaN,NaN,F,I,8260 ATLEE RD,"MOB 2, SUITE 319",MECHANICSVILLE,...,99223,"Initial hospital inpatient care, typically 70 ...",N,41.0,41.0,41.0,203.40,496.0,225.564634,155.800732
9847441,1992999874,JOFFE,GABRIELLA,NaN,NaN,F,I,8260 ATLEE RD,"MOB 2, SUITE 319",MECHANICSVILLE,...,99232,"Subsequent hospital inpatient care, typically ...",N,101.0,57.0,101.0,72.48,176.0,83.200000,57.390000
9847442,1992999874,JOFFE,GABRIELLA,NaN,NaN,F,I,8260 ATLEE RD,"MOB 2, SUITE 319",MECHANICSVILLE,...,99233,"Subsequent hospital inpatient care, typically ...",N,102.0,55.0,102.0,104.76,254.0,119.450784,82.450490
9847443,1992999874,JOFFE,GABRIELLA,NaN,NaN,F,I,8260 ATLEE RD,"MOB 2, SUITE 319",MECHANICSVILLE,...,99239,"Hospital discharge day management, more than 3...",N,49.0,49.0,49.0,107.98,262.0,123.950000,85.540000

In [37]:
provider.provider_type

0                        NaN
1          Internal Medicine
2          Internal Medicine
3          Internal Medicine
4          Internal Medicine
                 ...
9847439       Otolaryngology
9847440    Internal Medicine
9847441    Internal Medicine
9847442    Internal Medicine
9847443    Internal Medicine
Name: provider_type, Length: 9847444, dtype: object

In [17]:
provider.shape

NameError: name 'provider' is not defined

In [39]:
type(provider)

pandas.core.frame.DataFrame

In [38]:
provider.dtypes

npi                                   int64
nppes_provider_last_org_name         object
nppes_provider_first_name            object
nppes_provider_mi                    object
nppes_credentials                    object
nppes_provider_gender                object
nppes_entity_code                    object
nppes_provider_street1               object
nppes_provider_street2               object
nppes_provider_city                  object
nppes_provider_zip                   object
nppes_provider_state                 object
nppes_provider_country               object
provider_type                        object
medicare_participation_indicator     object
place_of_service                     object
hcpcs_code                           object
hcpcs_description                    object
hcpcs_drug_indicator                 object
line_srvc_cnt                       float64
bene_unique_cnt                     float64
bene_day_srvc_cnt                   float64
average_Medicare_allowed_amt        float64
average_submitted_chrg_amt          float64
average_Medicare_payment_amt        float64
average_Medicare_standard_amt       float64
dtype: object

In [40]:
provider.nppes_credentials.unique()

array([nan, 'M.D.', 'D.O.', ..., 'MA,', 'L.AC, PA-C', 'RN MSN HSA FNP-C'],
      dtype=object)

In [41]:
provider.nppes_credentials.nunique()

15985

In [42]:
#add_b=pd.read_excel('data/January 2020 Addendum B CORRECTION.02042020.xlsx')
hospital=pd.read_excel('data/2020_january_web_addendum_b.12312019.xlsx')

In [43]:
hospital.head(10)

,Unnamed: 0,Addendum B.-Final OPPS Payment by HCPCS Code for CY 2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,CPT codes and descriptions only are copyright ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCPCS Code,Short Descriptor,SI,APC,Relative Weight,Payment Rate,National Unadjusted Copayment,Minimum Unadjusted Copayment,Note: Actual copayments would be lower due to ...,* Indicates a Change
2,00100,Anesth salivary gland,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00102,Anesth repair of cleft lip,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00103,Anesth blepharoplasty,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00104,Anesth electroshock,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,00120,Anesth ear surgery,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,00124,Anesth ear exam,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,00126,Anesth tympanotomy,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,00140,Anesth procedures on eye,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
hospital.tail(10)

,Unnamed: 0,Addendum B.-Final OPPS Payment by HCPCS Code for CY 2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
16620,V5287,"Ald fm/dm receiver, nos",E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16621,V5288,Ald fm/dm transmitter ald,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16622,V5289,Ald fm/dm adapt/boot couplin,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16623,V5290,Ald transmitter microphone,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16624,V5298,Hearing aid noc,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16625,V5299,Hearing service,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16626,V5336,Repair communication device,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16627,V5362,Speech screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16628,V5363,Language screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16629,V5364,Dysphagia screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
hospital.shape

(16630, 10)

In [27]:
hospital.dtypes

Unnamed: 0                                                  object
Addendum B.-Final OPPS Payment by HCPCS Code for CY 2020    object
Unnamed: 2                                                  object
Unnamed: 3                                                  object
Unnamed: 4                                                  object
Unnamed: 5                                                  object
Unnamed: 6                                                  object
Unnamed: 7                                                  object
Unnamed: 8                                                  object
Unnamed: 9                                                  object
dtype: object

APCs or "Ambulatory Payment Classifications" are the government's method of paying facilities for outpatient services for the Medicare program. A part of the Federal Balanced Budget Act of 1997 required HCFA (now CMS) to create a new Medicare "Outpatient Prospective Payment System" (OPPS) for hospital outpatient services -analogous to the Medicare prospective payment system for hospital inpatients known as "Diagnosis Related Groups" or DRGs. This OPPS was implemented on August 1, 2000. APCs are an outpatient prospective payment system applicable only to hospitals, and have no impact on physician payments under the Medicare Physician Fee Schedule. APC payments are made only to hospitals when the Medicare outpatient is discharged from the ED or clinic or is transferred to another hospital (or other facility) which is not affiliated with the initial hospital where the patient received outpatient services. If the patient is admitted from a hospital clinic or ED, then there is no APC payment, and Medicare will pay the hospital under inpatient DRG methodology.

Each APC is composed of services which are similar in clinical intensity, resource utilization and cost. All services (identified by submission of CMS' Healthcare Common Procedure Coding System (HCPCS) codes on the hospital's UB 04 claim form) which are grouped under a specific APC result in an annually updated Medicare "prospective payment" for that particular APC. (Many HCPCS codes are derived directly from the AMA CPT.)  Since this payment is a prospective and "fixed" payment to the hospital, the hospital is at risk for potential "profit or loss" with each APC payment it receives. The payments are calculated by multiplying the APCs relative weight by the OPPS conversion factor and then there is a minor adjustment for geographic location. The payment is divided into Medicare's portion and patient co-pay. Co-pays vary between 20 and 40% of the APC payment rate. Eventually this percent will be capped at 20% of the payment rate.  A status indicator is assigned to each code to identify how the service is priced for payment.  For example, Status Indicator (SI) “F” - Corneal Tissue Acquisition; Certain CRNA Services and Hepatitis B Vaccines, is not paid under OPPS but is paid on reasonable cost basis.   https://www.acep.org/administration/reimbursement/reimbursement-faqs/apc-ambulatory-payment-classifications-faq/#question0

In [28]:
hospital.shape

(16630, 10)

In [29]:
patient=pd.read_excel('data/MUP_OHP_R19_P04_V10_D17_APC_Provider.xlsx')

In [79]:
patient.head(10)

,"Provider Comprehensive APC Summary for Medicare Outpatient Prospective Payment System Hospitals, CY17",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NOTE: Data summary includes services furnished...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,APC records with fewer than 11 services have b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Provider ID,Provider Name,Provider Street Address,Provider City,Provider\nState,Provider\nZip Code,Provider\nHospital Referral Region\n(HRR),APC,APC\nDescription,Beneficiaries,Comprehensive APC\nServices,Average\nEstimated\nTotal\nSubmitted\nCharges,Average\nMedicare\nAllowed\nAmount,Average\nMedicare\nPayment\nAmount,Outlier\nComprehensive\nAPC\nServices,Average\nMedicare\nOutlier\nAmount
5,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249,259,9575.01,1038.45,826.278,NaN,NaN
6,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52,53,12578.3,1792.6,1423.25,NaN,NaN
7,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26,27,11337.6,2113.58,1683.99,0,0
8,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23,23,17116.2,3737.14,2977.55,0,0
9,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17,17,7382.73,1029.46,820.21,0,0

In [80]:
patient.tail(10)

,"Provider Comprehensive APC Summary for Medicare Outpatient Prospective Payment System Hospitals, CY17",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
61774,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5191,Level 1 Endovascular Procedures,70,70,17180.3,2682.39,1826.97,NaN,NaN
61775,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5193,Level 3 Endovascular Procedures,29,31,58238.4,9384.71,8068.71,0,0
61776,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5213,Level 3 Electrophysiologic Procedures,21,21,93469.7,15427.8,14111.8,0,0
61777,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5223,Level 3 Pacemaker and Similar Procedures,12,12,52318,9059.63,7743.63,0,0
61778,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5302,Level 2 Upper GI Procedures,17,18,14412.7,1286.13,1024.72,NaN,NaN
61779,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5361,Level 1 Laparoscopy and Related Services,18,18,54778.8,3866.82,3044.48,13,1623.73
61780,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5373,Level 3 Urology and Related Services,11,11,28237.6,1469.87,1147.78,NaN,NaN
61781,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5375,Level 5 Urology and Related Services,20,21,35109.7,3356.89,2674.59,NaN,NaN
61782,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5431,Level 1 Nerve Procedures,NaN,12,25195,1506.38,1200.2,NaN,NaN
61783,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,8011,Comprehensive Observation Services,156,165,26580.5,2141.54,1706.27,40,1705.11

In [81]:
patient.shape

(61784, 16)

In [82]:
patient.dtypes

Provider Comprehensive APC Summary for Medicare Outpatient Prospective Payment System Hospitals, CY17    object
Unnamed: 1                                                                                               object
Unnamed: 2                                                                                               object
Unnamed: 3                                                                                               object
Unnamed: 4                                                                                               object
Unnamed: 5                                                                                               object
Unnamed: 6                                                                                               object
Unnamed: 7                                                                                               object
Unnamed: 8                                                                                               object
Unnamed: 9                                                                                               object
Unnamed: 10                                                                                              object
Unnamed: 11                                                                                              object
Unnamed: 12                                                                                              object
Unnamed: 13                                                                                              object
Unnamed: 14                                                                                              object
Unnamed: 15                                                                                              object
dtype: object

In [64]:
zip_cbsa=pd.read_excel("data/ZIP_CBSA_032020.xlsx")

In [65]:
zip_cbsa

         ZIP   CBSA  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0        501  35620        0.0        1.0        0.0        1.0
1        601  38660        1.0        1.0        1.0        1.0
2        602  10380        1.0        1.0        1.0        1.0
3        603  10380        1.0        1.0        1.0        1.0
4        604  10380        1.0        1.0        1.0        1.0
...      ...    ...        ...        ...        ...        ...
47410  99925  99999        0.0        0.0        1.0        1.0
47411  99926  99999        0.0        0.0        1.0        1.0
47412  99927  99999        0.0        0.0        1.0        1.0
47413  99928  28540        0.0        0.0        1.0        1.0
47414  99929  99999        0.0        0.0        1.0        1.0

[47415 rows x 6 columns]

In [66]:
zip_cbsa.dtypes

ZIP            int64
CBSA           int64
RES_RATIO    float64
BUS_RATIO    float64
OTH_RATIO    float64
TOT_RATIO    float64
dtype: object

In [67]:
zip_cbsa.shape

(47415, 6)